export type CliTool = {
  id: string
  label: string
  /** Filename of the agent icon in QuickPick, relative to images/agents/. */
  icon: string
  /** Codicon / ThemeIcon identifier for terminal tabs (persists across window reload). */
  themeIcon: string
  description?: string
  /** Shell command to launch. Use `{port}` as a placeholder for HTTP-aware CLIs. */
  command: string
  hasHttpApi: boolean
  /** Env var the CLI reads to discover the port it should serve on. */
  portEnvVar?: string
  appendPromptPath?: string
  readyCheckPath?: string
  /** Extra environment variables to set when launching the terminal. */
  extraEnv?: Record<string, string>
  /** Reopens a specific past session; `{sessionId}` is substituted. Only for CLIs verified to accept an id. */
  resumeCommand?: string
  /** Reopens the most recent session when the CLI cannot address one by id. */
  continueCommand?: string
  /** Tool id the session-history parsers stamp on this CLI's transcripts, when it differs (variants sharing a CLI). */
  historyToolId?: string
}

// Ordered roughly by popularity. Every entry is offered to the user; nothing
// checks whether the CLI is actually installed, so an absent one fails at launch.
// Commands carry the CLI's own permission-bypass flag where one exists — see the
// per-entry notes for the tools that have no such flag. Icons are sourced from
// the Orca ADE agent glyphs/favicons (github.com/stablyai/orca). Each CLI ships a
// light and dark variant (images/agents-light, images/agents-dark).
export const CLI_TOOLS: CliTool[] = [
  {
    id: "claude",
    label: "Claude Code",
    icon: "claude.svg",
    themeIcon: "sparkle",
    description: "Anthropic Claude Code CLI",
    command: "claude --dangerously-skip-permissions",
    hasHttpApi: false,
    resumeCommand: "claude --resume {sessionId} --dangerously-skip-permissions",
  },
  {
    id: "claude-agent-teams",
    label: "Claude Agent Teams",
    icon: "claude.svg",
    themeIcon: "organization",
    description: "Claude Code multi-agent teams",
    command: "CLAUDE_CODE_EXPERIMENTAL_AGENT_TEAMS=1 claude --dangerously-skip-permissions",
    hasHttpApi: false,
    resumeCommand: "CLAUDE_CODE_EXPERIMENTAL_AGENT_TEAMS=1 claude --resume {sessionId} --dangerously-skip-permissions",
    historyToolId: "claude",
  },
  {
    id: "codex",
    label: "Codex CLI",
    icon: "codex.svg",
    themeIcon: "code",
    description: "OpenAI Codex CLI",
    command: "codex --dangerously-bypass-approvals-and-sandbox",
    hasHttpApi: false,
    resumeCommand: "codex resume {sessionId} --dangerously-bypass-approvals-and-sandbox",
  },
  {
    id: "grok",
    label: "Grok",
    icon: "grok.png",
    themeIcon: "zap",
    description: "xAI Grok CLI",
    command: "grok --permission-mode bypassPermissions",
    hasHttpApi: false,
    resumeCommand: "grok --permission-mode bypassPermissions --resume {sessionId}",
  },
  {
    id: "copilot",
    label: "GitHub Copilot CLI",
    icon: "copilot.svg",
    themeIcon: "copilot",
    description: "GitHub Copilot in the terminal",
    command: "copilot --yolo",
    hasHttpApi: false,
    continueCommand: "copilot --yolo --continue",
    resumeCommand: "copilot --yolo --resume {sessionId}",
  },
  {
    id: "opencode",
    label: "opencode",
    icon: "opencode.svg",
    themeIcon: "terminal",
    description: "opencode TUI (HTTP-aware)",
    command: "opencode --port {port} --auto",
    hasHttpApi: true,
    portEnvVar: "_EXTENSION_OPENCODE_PORT",
    appendPromptPath: "/tui/append-prompt",
    readyCheckPath: "/app",
    extraEnv: { OPENCODE_CALLER: "vscode" },
    continueCommand: "opencode --port {port} --auto --continue",
    resumeCommand: "opencode --port {port} --auto --session {sessionId}",
  },
  {
    id: "mimo",
    label: "MiMo Code",
    icon: "mimo-code.png",
    themeIcon: "symbol-keyword",
    description: "MiMo Code coding agent",
    command: "mimo",
    hasHttpApi: false,
    continueCommand: "mimo --continue",
    resumeCommand: "mimo --session {sessionId}",
  },
  {
    id: "pi",
    label: "Pi",
    icon: "pi.svg",
    themeIcon: "symbol-misc",
    description: "Pi coding agent",
    command: "pi",
    hasHttpApi: false,
    continueCommand: "pi --continue",
    resumeCommand: "pi --session-id {sessionId}",
  },
  {
    id: "omp",
    label: "OMP",
    icon: "omp.svg",
    themeIcon: "sparkle",
    description: "Oh My Pi coding agent",
    command: "omp",
    hasHttpApi: false,
    continueCommand: "omp --continue",
    resumeCommand: "omp --resume {sessionId}",
  },
  {
    id: "antigravity",
    label: "Antigravity",
    icon: "antigravity.png",
    themeIcon: "rocket",
    description: "Google Antigravity CLI",
    command: "agy --dangerously-skip-permissions",
    hasHttpApi: false,
    continueCommand: "agy --dangerously-skip-permissions --continue",
  },
  {
    id: "amp",
    label: "Amp",
    icon: "amp.png",
    themeIcon: "symbol-event",
    description: "Sourcegraph Amp coding agent",
    command: "amp --dangerously-allow-all",
    hasHttpApi: false,
    continueCommand: "amp --dangerously-allow-all threads continue --last",
    resumeCommand: "amp --dangerously-allow-all threads continue {sessionId}",
  },
  {
    id: "kilo",
    label: "Kilocode",
    icon: "kilo.svg",
    themeIcon: "flame",
    description: "Kilo Code coding agent (opencode fork, 500+ models)",
    command: "kilo",
    hasHttpApi: false,
    continueCommand: "kilo --continue",
    resumeCommand: "kilo --session {sessionId}",
  },
  {
    id: "cline",
    label: "Cline",
    icon: "cline.png",
    themeIcon: "robot",
    description: "Cline open-source coding agent CLI",
    command: "cline --auto-approve true",
    hasHttpApi: false,
    resumeCommand: "cline --auto-approve true --id {sessionId}",
  },
  {
    id: "command-code",
    label: "Command Code",
    icon: "command-code.png",
    themeIcon: "terminal-powershell",
    description: "CommandCode coding agent",
    command: "command-code --yolo",
    hasHttpApi: false,
    continueCommand: "command-code --yolo --continue",
    resumeCommand: "command-code --yolo --resume {sessionId}",
  },
  {
    id: "droid",
    label: "Droid",
    icon: "droid.svg",
    themeIcon: "hubot",
    description: "Factory AI Droid coding agent",
    command: "droid",
    hasHttpApi: false,
    continueCommand: "droid --resume",
    resumeCommand: "droid --resume {sessionId}",
  },
  {
    id: "prime-agent",
    label: "Prime Agent",
    icon: "prime-agent.png",
    themeIcon: "symbol-class",
    description: "Prime Agent coding agent",
    command: "prime-agent",
    hasHttpApi: false,
    continueCommand: "prime-agent --continue",
    resumeCommand: "prime-agent -r {sessionId}",
  },
  {
    id: "aider",
    label: "Aider",
    icon: "aider.svg",
    themeIcon: "git-merge",
    description: "Aider AI pair-programming CLI",
    command: "aider --yes-always",
    hasHttpApi: false,
    continueCommand: "aider --yes-always --restore-chat-history",
  },
  {
    id: "goose",
    label: "Goose",
    icon: "goose.png",
    themeIcon: "beaker",
    description: "Block Goose coding agent",
    command: "GOOSE_MODE=auto goose",
    hasHttpApi: false,
    continueCommand: "GOOSE_MODE=auto goose session --resume",
    resumeCommand: "GOOSE_MODE=auto goose session --resume --session-id {sessionId}",
  },
  {
    id: "kiro",
    label: "Kiro",
    icon: "kiro.png",
    themeIcon: "key",
    description: "AWS Kiro CLI coding agent",
    command: "kiro-cli --trust-all-tools",
    hasHttpApi: false,
    continueCommand: "kiro-cli --trust-all-tools chat --resume",
  },
  {
    id: "crush",
    label: "Charm / Crush",
    icon: "crush.png",
    themeIcon: "heart",
    description: "Charm Crush coding agent",
    command: "crush --yolo",
    hasHttpApi: false,
    continueCommand: "crush --yolo --continue",
  },
  {
    id: "aug",
    label: "Auggie",
    icon: "aug.png",
    themeIcon: "symbol-variable",
    description: "Augment Code CLI",
    command: "auggie",
    hasHttpApi: false,
    continueCommand: "auggie --continue",
  },
  {
    id: "continue",
    label: "Continue",
    icon: "continue.png",
    themeIcon: "play",
    description: "Continue CLI",
    command: 'cn --allow "*"',
    hasHttpApi: false,
    continueCommand: "cn --allow \"*\" --resume",
  },
  {
    id: "cursor",
    label: "Cursor",
    icon: "cursor.png",
    themeIcon: "symbol-field",
    description: "Cursor Agent CLI",
    command: "cursor-agent --yolo",
    hasHttpApi: false,
    continueCommand: "cursor-agent --yolo --continue",
    resumeCommand: "cursor-agent --yolo --resume {sessionId}",
  },
  {
    id: "kimi",
    label: "Kimi",
    icon: "kimi.png",
    themeIcon: "globe",
    description: "Kimi Code CLI",
    command: "kimi --yolo",
    hasHttpApi: false,
    continueCommand: "kimi --yolo --continue",
    resumeCommand: "kimi --yolo --session {sessionId}",
  },
  {
    id: "mistral-vibe",
    label: "Mistral Vibe",
    icon: "mistral-vibe.png",
    themeIcon: "radio-tower",
    description: "Mistral Vibe coding agent",
    command: "vibe --agent auto-approve",
    hasHttpApi: false,
    continueCommand: "vibe --agent auto-approve --continue",
  },
  {
    id: "qwen-code",
    label: "Qwen Code",
    icon: "qwen-code.png",
    themeIcon: "circuit-board",
    description: "Qwen Code CLI",
    command: "qwen --approval-mode yolo",
    hasHttpApi: false,
    continueCommand: "qwen --approval-mode yolo --continue",
  },
  {
    id: "hermes",
    label: "Hermes",
    icon: "hermes.png",
    themeIcon: "send",
    description: "Nous Research Hermes agent",
    command: "hermes --yolo",
    hasHttpApi: false,
    continueCommand: "hermes --yolo --continue",
  },
  {
    id: "devin",
    label: "Devin",
    icon: "devin.png",
    themeIcon: "robot",
    description: "Cognition Devin CLI",
    command: "devin --permission-mode bypass",
    hasHttpApi: false,
    continueCommand: "devin --permission-mode bypass --continue",
  },
]
